from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class LocaleLabels:
    parameters: str
    returns: str
    raises: str
    edge_cases: str
    side_effects: str
    examples: str
    see_also: str
    fields: str
    inheritance: str
    exports: str
    classes: str
    functions: str
    contents: str
    methods: str
    root_modules: str
    packages: str
    modules: str
    module: str
    description: str
    package: str
    module_count: str
    back_to_project: str
    back_to_index: str
    back_to_package: str
    default_description: str


_LABELS: dict[str, LocaleLabels] = {
    "ru": LocaleLabels(
        parameters="Параметры",
        returns="Возвращаемое значение",
        raises="Исключения",
        edge_cases="Граничные случаи",
        side_effects="Побочные эффекты",
        examples="Примеры",
        see_also="Смотрите также",
        fields="Поля",
        inheritance="Наследование",
        exports="Экспорт",
        classes="Классы",
        functions="Функции",
        contents="Содержание",
        methods="Методы",
        root_modules="Корневые модули",
        packages="Пакеты",
        modules="Модули",
        module="Модуль",
        description="Описание",
        package="Пакет",
        module_count="Модулей",
        back_to_project="← К проекту",
        back_to_index="← Индекс",
        back_to_package="←",
        default_description="Документация проекта, сгенерированная AnDocGen.",
    ),
    "en": LocaleLabels(
        parameters="Parameters",
        returns="Returns",
        raises="Raises",
        edge_cases="Edge cases",
        side_effects="Side effects",
        examples="Examples",
        see_also="See also",
        fields="Fields",
        inheritance="Inheritance",
        exports="Exports",
        classes="Classes",
        functions="Functions",
        contents="Contents",
        methods="Methods",
        root_modules="Root modules",
        packages="Packages",
        modules="Modules",
        module="Module",
        description="Description",
        package="Package",
        module_count="Modules",
        back_to_project="← Back to project",
        back_to_index="← Back to index",
        back_to_package="←",
        default_description="Project documentation generated by AnDocGen.",
    ),
}


def get_labels(language: str) -> LocaleLabels:
    return _LABELS.get(language, _LABELS["en"])
