# AUTO-GENERATED from config.schema.yaml — do not edit manually.
# Regenerate: ./scripts/generate_config_models.sh

# generated by datamodel-codegen:
#   filename:  config.schema.yaml

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field


class ProjectConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str | None = Field(
        '',
        description='Отображаемое имя проекта; если пусто — используется имя корневого каталога.',
        examples=['', 'my_project'],
    )
    description: str | None = Field(
        '',
        description='Краткое описание проекта; если пусто — извлекается из метаданных репозитория.',
    )
    readme_path: str | None = Field(
        '',
        description='Путь к файлу описания проекта относительно корня.',
        examples=['', 'README.md', 'docs/README.md'],
    )


class Implementation(StrEnum):
    filesystem = 'filesystem'


class DiscoveryConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    implementation: Implementation | None = Field(
        'filesystem', description='Реализация модуля обнаружения исходных файлов.'
    )
    extensions: list[str] | None = Field(
        ['.py'],
        description='Список расширений файлов, подлежащих сканированию.',
        examples=[['.py'], ['.py', '.pyi']],
    )
    exclude_dirs: list[str] | None = Field(
        [
            '__pycache__',
            '.git',
            '.venv',
            'venv',
            '.andocgen',
            'generated_docs',
            'node_modules',
        ],
        description='Имена каталогов, исключаемых из обхода файловой системы.',
    )


class Implementation1(StrEnum):
    field_ = ''
    python_ast = 'python_ast'


class Language(StrEnum):
    python = 'python'


class ExtractionConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    implementation: Implementation1 | None = Field(
        '',
        description='Реализация синтаксического разбора; пустое значение — автоматический выбор по полю language.',
        examples=['', 'python_ast'],
    )
    language: Language | None = Field(
        'python',
        description='Язык исходного кода документируемого проекта.',
        examples=['python'],
    )


class Implementation2(StrEnum):
    static = 'static'


class CallGraphConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    implementation: Implementation2 | None = Field(
        'static', description='Реализация построения графа вызовов между сущностями.'
    )


class Implementation3(StrEnum):
    default = 'default'


class Prompt(StrEnum):
    sectioned = 'sectioned'


class ContextConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    implementation: Implementation3 | None = Field(
        'default', description='Реализация сборщика контекста для каждой сущности.'
    )
    prompt: Prompt | None = Field(
        'sectioned', description='Реализация формирования запроса к языковой модели.'
    )
    include_source_body: bool | None = Field(
        True, description='Включать полный текст исходного фрагмента в контекст модели.'
    )
    include_imports: bool | None = Field(
        True, description='Включать объявления зависимостей и импортов в контекст.'
    )
    include_call_graph: bool | None = Field(
        True,
        description='Включать сведения о связанных сущностях и неразрешённых вызовах.',
    )
    readme_limit: int | None = Field(
        2000,
        description='Максимальная длина фрагмента описания проекта в символах.',
        examples=[2000, 4000],
    )
    max_context_chars: int | None = Field(
        32000,
        description='Максимальная длина пользовательской части запроса в символах.',
        examples=[32000, 64000],
    )


class OllamaProvider(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    base_url: str | None = Field(
        'http://localhost:11434',
        description='Базовый URL HTTP API провайдера Ollama.',
        examples=['http://localhost:11434'],
    )
    model: str | None = Field(
        'llama3',
        description='Идентификатор модели на стороне провайдера.',
        examples=['llama3', 'qwen2.5-coder:7b'],
    )
    timeout: float | None = Field(
        120.0,
        description='Таймаут одного HTTP-запроса в секундах.',
        examples=[120, 300],
    )


class OpenAIProvider(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    base_url: str | None = Field(
        'https://api.openai.com/v1',
        description='Базовый URL API, совместимого с протоколом OpenAI.',
        examples=['https://api.openai.com/v1'],
    )
    api_key_env: str | None = Field(
        'OPENAI_API_KEY',
        description='Имя переменной окружения, из которой читается ключ доступа.',
        examples=['OPENAI_API_KEY'],
    )
    model: str | None = Field(
        'gpt-4o-mini',
        description='Идентификатор модели на стороне провайдера.',
        examples=['gpt-4o-mini', 'gpt-4o'],
    )
    project: str | None = Field(
        '', description='Идентификатор проекта у облачного провайдера.', examples=['']
    )
    timeout: float | None = Field(
        120.0, description='Таймаут клиента в секундах.', examples=[120]
    )
    temperature: float | None = Field(
        None, description='Параметр случайности генерации.', examples=[None, 0.7]
    )
    max_tokens: int | None = Field(
        None,
        description='Верхний предел длины ответа в токенах.',
        examples=[None, 4096],
    )


class Providers(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ollama: OllamaProvider | None = None
    openai: OpenAIProvider | None = None


class Implementation4(StrEnum):
    llm = 'llm'


class Provider(StrEnum):
    mock = 'mock'
    ollama = 'ollama'
    openai = 'openai'


class GenerationConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    implementation: Implementation4 | None = Field(
        'llm', description='Реализация модуля генерации документации.'
    )
    provider: Provider | None = Field(
        'mock',
        description='Провайдер языковой модели для генерации текста.',
        examples=['mock', 'ollama', 'openai'],
    )
    language: str | None = Field(
        'ru', description='Язык создаваемой документации.', examples=['ru', 'en']
    )
    incremental: bool | None = Field(
        True, description='Пропускать файлы, не изменившиеся с предыдущего прогона.'
    )
    workers: int | None = Field(
        1,
        description='Число параллельных запросов к модели в пределах одной волны зависимостей.',
        examples=[1, 4],
    )
    max_retries: int | None = Field(
        2,
        description='Число повторных попыток при ошибке разбора ответа или блокирующей валидации.',
        examples=[2, 3],
    )
    providers: Providers | None = None


class Implementation5(StrEnum):
    structured = 'structured'


class BlockingFallback(StrEnum):
    retry = 'retry'
    strip_examples = 'strip_examples'
    error = 'error'


class ValidationConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    implementation: Implementation5 | None = Field(
        'structured',
        description='Реализация модуля проверки сгенерированной документации.',
    )
    check_completeness: bool | None = Field(
        True,
        description='Проверять полноту описания параметров и возвращаемых значений.',
    )
    check_consistency: bool | None = Field(
        True,
        description='Проверять соответствие документации фактической сигнатуре сущности.',
    )
    check_structure: bool | None = Field(
        True,
        description='Проверять структуру ответа модели (зарезервировано, пока не применяется).',
    )
    check_representation: bool | None = Field(
        True,
        description='Проверять наличие ключевых разделов в итоговом представлении.',
    )
    check_text_quality: bool | None = Field(
        True,
        description='Проверять качество текста — длину, язык и показатели сложности.',
    )
    complexity_warning_threshold: int | None = Field(
        20,
        description='Порог метрики сложности, при превышении которого выдаётся предупреждение.',
        examples=[20, 30],
    )
    min_summary_length: int | None = Field(
        10,
        description='Минимальная длина краткого описания до выдачи предупреждения.',
        examples=[10],
    )
    retry_on_blocking: bool | None = Field(
        True,
        description='Повторять генерацию при блокирующих замечаниях предварительной проверки.',
    )
    blocking_fallback: BlockingFallback | None = Field(
        'retry',
        description='Стратегия обработки после исчерпания повторов при блокирующих замечаниях.',
        examples=['retry', 'strip_examples', 'error'],
    )


class Implementation6(StrEnum):
    markdown = 'markdown'


class OutputConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    implementation: Implementation6 | None = Field(
        'markdown', description='Реализация модуля записи документации на диск.'
    )
    directory: str | None = Field(
        './generated_docs',
        description='Корневой каталог для сохранения сгенерированных файлов.',
        examples=['./generated_docs', './docs'],
    )
    format: str | None = Field(
        'markdown',
        description='Формат выходных файлов (зарезервировано; фактически задаётся implementation).',
    )
    cache_path: str | None = Field(
        '',
        description='Каталог кэша контрольных сумм; пустое значение — каталог по умолчанию под output.directory.',
        examples=[''],
    )


class Implementation7(StrEnum):
    file = 'file'


class ReportingConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    implementation: Implementation7 | None = Field(
        'file', description='Реализация модуля отчётности о прогоне.'
    )
    logs_dir: str | None = Field(
        '',
        description='Каталог журналов прогона; пустое значение — каталог по умолчанию под output.directory.',
        examples=[''],
    )
    summary_file: str | None = Field(
        'summary.txt',
        description='Имя файла краткой текстовой сводки прогона.',
        examples=['summary.txt'],
    )
    detail_file: str | None = Field(
        'detail.json',
        description='Имя файла структурированного отчёта о замечаниях и ошибках.',
        examples=['detail.json'],
    )
    trace_file: str | None = Field(
        'trace.log',
        description='Имя файла подробной трассировки этапов и запросов.',
        examples=['trace.log'],
    )
    log_llm_content: bool | None = Field(
        True,
        description='Записывать в трассировку полный текст запросов и ответов модели.',
        examples=[True, False],
    )
    trace_max_chars: int | None = Field(
        12000,
        description='Максимальная длина записываемого фрагмента запроса или ответа в трассировке.',
        examples=[12000, 24000],
    )
    quiet: bool | None = Field(
        False,
        description='Подавлять вывод прогресса и итоговой сводки в консоль.',
        examples=[False, True],
    )


class AndocgenConfiguration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    project: ProjectConfig | None = None
    discovery: DiscoveryConfig | None = None
    extraction: ExtractionConfig | None = None
    call_graph: CallGraphConfig | None = None
    context: ContextConfig | None = None
    generation: GenerationConfig | None = None
    validation: ValidationConfig | None = None
    output: OutputConfig | None = None
    reporting: ReportingConfig | None = None
